In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
from tqdm import tqdm

In [3]:
Tickers = [
    "BHP.AX", "CBA.AX", "CSL.AX",
    "NAB.AX", "WBC.AX", "ANZ.AX",
    "WES.AX", "MQG.AX", "WOW.AX", "TLS.AX"
]

In [4]:
testdata = yf.download("BHP.AX", start="2010-01-01")
testdata.head()

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/2671760116.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  testdata = yf.download("BHP.AX", start="2010-01-01")
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker         BHP.AX     BHP.AX     BHP.AX     BHP.AX    BHP.AX
Date
2010-01-04  14.224621  14.284055  14.102450  14.115657   4436014
2010-01-05  14.290659  14.409528  14.274150  14.363301  10918398
2010-01-06  14.468963  14.478869  14.376509  14.389717   7806934
2010-01-07  14.452451  14.574622  14.445847  14.498678   7964069
2010-01-08  14.402924  14.485471  14.363300  14.426036   5510642

In [5]:
Allstocks = []

for ticker in tqdm(Tickers):
    df = yf.download(ticker, start="2010-01-01", progress=False)
    df = df.reset_index()
    df["Ticker"] = ticker
    Allstocks.append(df)

StocksData = pd.concat(Allstocks, ignore_index=True)

  0%|          | 0/10 [00:00<?, ?it/s]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 10%|█         | 1/10 [00:01<00:12,  1.36s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 20%|██        | 2/10 [00:05<00:23,  2.95s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 30%|███       | 3/10 [00:06<00:16,  2.30s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 40%|████      | 4/10 [00:08<00:12,  2.16s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 50%|█████     | 5/10 [00:11<00:10,  2.17s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 60%|██████    | 6/10 [00:12<00:08,  2.08s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 70%|███████   | 7/10 [00:14<00:05,  1.91s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 80%|████████  | 8/10 [00:16<00:03,  1.79s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 90%|█████████ | 9/10 [00:17<00:01,  1.71s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_8808/885661854.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
100%|██████████| 10/10 [00:20<00:00,  2.06s/it]

In [7]:
StocksData.head(10)

Price,Date,Close,High,Low,Open,Volume,Ticker,Close,High,Low,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,,BHP.AX,BHP.AX,BHP.AX,BHP.AX,BHP.AX,,CBA.AX,CBA.AX,CBA.AX,...,WOW.AX,WOW.AX,WOW.AX,WOW.AX,WOW.AX,TLS.AX,TLS.AX,TLS.AX,TLS.AX,TLS.AX
0,2010-01-04,14.224621,14.284055,14.102450,14.115657,4436014.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,14.290656,14.409525,14.274148,14.363298,10918398.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,14.468966,14.478872,14.376511,14.389720,7806934.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,14.452449,14.574620,14.445845,14.498676,7964069.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,14.402922,14.485469,14.363298,14.426034,5510642.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2010-01-11,14.683587,14.690191,14.505284,14.521794,11048942.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2010-01-12,14.360001,14.495379,14.343491,14.478870,10769158.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2010-01-13,14.237826,14.277450,14.151977,14.181694,15675825.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2010-01-14,14.455751,14.544904,14.317072,14.346789,12295931.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2010-01-15,14.412827,14.422733,14.290656,14.386412,16956523.0,BHP.AX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN